language: php

php:
  - "5.3"
  - "5.4"
  - "5.5"
  - "5.6"
  - "7.0"
  - "7.1"
  - "hhvm"
  - "nightly"

matrix:
  fast_finish: true
  allow_failures:
    - php: "nightly"

sudo: false

install:
  - composer install

after_success:
  - bash <(curl -s https://codecov.io/bash)

cache:
  directories:
    - $HOME/.composer/cache
